core: udev: sync with poky recipe
 - work and remove on all HAVE TO EVALUATE hints
 - support start/stop in sysvinit script
 - support and enable udev-cache

Signed-off-by: Stephan Linz <stephan.linz@clondiag.com>

diff --git a/recipes-core/udev/udev/init b/recipes-core/udev/udev/init
--- a/recipes-core/udev/udev/init
+++ b/recipes-core/udev/udev/init
@@ -19,6 +19,8 @@ export TZ=/etc/localtime
 [ -f /etc/default/udev-cache ] && . /etc/default/udev-cache
 [ -f /etc/udev/udev.conf ] && . /etc/udev/udev.conf
 
+[ -z "$DEVSETTLETO" ] && DEVSETTLETO=3
+
 readfile () {
    filename=$1
    READDATA=""
@@ -35,17 +37,17 @@ case "$1" in
     # propagate /dev from /sys
     echo "Starting udev"
 
-    # Check for requireed devtmpfs before trying to start udev and
+    # Check for requireed tmpfs before trying to start udev and
     # mount a no-existant fs.
-    if ! grep -q devtmpfs /proc/filesystems
+    if ! grep -q tmpfs /proc/filesystems
     then
-        echo "Missing devtmpfs, which is required for udev to run";
+        echo "Missing tmpfs, which is required for udev to run";
         echo "Halting..."
         halt
     fi
-    # mount the devtmpfs on /dev, if not already done
-    LANG=C awk '$2 == "/dev" && ($3 == "devtmpfs") { exit 1 }' /proc/mounts && {
-            mount -n -o mode=0755 -t devtmpfs none "/dev"
+    # mount the tmpfs on /dev, if not already done
+    LANG=C awk '$2 == "/dev" && ($3 == "tmpfs") { exit 1 }' /proc/mounts && {
+            mount -n -o mode=0755 -t tmpfs none "/dev"
     }
     [ -e /dev/pts ] || mkdir -m 0755 /dev/pts
     [ -e /dev/shm ] || mkdir -m 1777 /dev/shm
@@ -69,14 +71,24 @@ case "$1" in
                     if [ "$READDATA" = "$VERSION$CMDLINE$DEVICES$ATAGS" ]; then
                             (cd /; tar xf $DEVCACHE > /dev/null 2>&1)
                             not_first_boot=1
+                            [ "$VERBOSE" != "no" ] && echo "udev: using cache file $DEVCACHE"
+                            [ -e /dev/shm/udev.cache ] && rm -f /dev/shm/udev.cache
+                    else
+                            echo "$VERSION$CMDLINE$DEVICES$ATAGS" > /dev/shm/udev.cache
                     fi
 
+            else
                     echo "$VERSION$CMDLINE$DEVICES$ATAGS" > /dev/shm/udev.cache
             fi
     fi
 
     # make_extra_nodes
     killproc udevd > "/dev/null" 2>&1
+
+    if [ -e /etc/dev.tar ]; then # HAVE TO EVALUATE (see above)
+	    (cd /; tar xf /etc/dev.tar 2>&1 | grep -v 'time stamp' || true)
+	    not_first_boot=1
+    fi
 
     # trigger the sorted events
     echo -e '\000\000\000\000' > /proc/sys/kernel/hotplug
@@ -85,7 +97,7 @@ case "$1" in
     udevadm control --env=STARTUP=1
     if [ "$not_first_boot" != "" ];then
             udevadm trigger --action=add --subsystem-nomatch=tty --subsystem-nomatch=mem --subsystem-nomatch=vc --subsystem-nomatch=vtconsole --subsystem-nomatch=misc --subsystem-nomatch=dcon --subsystem-nomatch=pci_bus  --subsystem-nomatch=graphics	 --subsystem-nomatch=backlight --subsystem-nomatch=video4linux	--subsystem-nomatch=platform
-            (udevadm settle --timeout=3; udevadm control --env=STARTUP=)&
+            (udevadm settle --timeout=$DEVSETTLETO; udevadm control --env=STARTUP=)&
     else
             udevadm trigger --action=add
             udevadm settle
